<a href="https://colab.research.google.com/github/Suryapv26/grokking/blob/main/grokking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print("Output After Training:")
print( l1)


[[-4.35138810e-01 -4.97614283e-01 -9.98313253e-01  3.38146197e-01]
 [ 4.44053139e-01  5.87327950e-01  7.98973906e-01  4.87033608e-01]
 [ 1.61076120e-04  7.79269362e-02  5.32096810e-01 -1.22278564e-01]]


In [ ]:
print(syn1)

[[  7.64943484]
 [  5.79155226]
 [-11.76607748]
 [  5.82473144]]


In [ ]:
syn1 = 2*np.random.random((4,1)) - 1
syn1

array([[-0.45450275],
       [-0.84102856],
       [-0.19527306],
       [-0.35265807]])

chapter3-code


In [7]:
import numpy as np
ih_wts = np.array([[0.1,0.2,-0.1],
                   [-0.1,0.1,0.9],
                   [0.1,0.4,0.1]]).T
hp_wt = np.array([[0.3,1.1,-0.3],
                   [0.1,0.2,0.0],
                  [0.0,1.3,0.1]]).T

weights = [ih_wts,hp_wt]

def neural(ip ,wts):
  print(ip,wts[0])
  hid = ip.dot(wts[0])
  print(hid)
  pred = hid.dot(wts[1])
  return pred

t = np.array([8.5,9.5,9.9,9.0])
w = np.array([0.65,0.8,0.8,0.9])
n = np.array([1.2,1.3,0.5,1.0])

input = np.array([t[0],w[0],n[0]])
#print(input,weights)
pred = neural(input,weights)
print(pred)

[8.5  0.65 1.2 ] [[ 0.1 -0.1  0.1]
 [ 0.2  0.1  0.4]
 [-0.1  0.9  0.1]]
[0.86  0.295 1.23 ]
[0.2135 0.145  0.5065]
